version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
    environment:
      - APP_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:1.18.0
    container_name: my-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network        

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: my-laravel-node
    container_name: my-laravel-node
    ports:
    - "3000:3000"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    networks:
      - app-network

  db:
    image: postgres:14.10
    container_name: my-postgresql
    restart: unless-stopped
    environment: 
      DB_DATABASE: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/postgresql
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local